name: Checks

env:
  NODE_VERSION: 18.16.1

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: geonetwork/geonetwork-ui
          path: './geonetwork-ui'
      - name: Build the gn-ui backend
        run: sudo docker-compose -f geonetwork-ui/support-services/docker-compose.yml up -d init

      - name: Install dependencies
        run: npm i -f

      - name: Run tests
        run: npx nx e2e mel-datahub-e2e
